version: '3.4'

services:
  gaymersbot:
    image: gaymersbot
    container_name: gaymersbot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 80:80
