version: '3.4'

services:
  gaymersbot:
    image: gaymersbot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
